[package]
name = "iron-and-blood-launcher"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.83"
glib = "0.19.7"
gtk4 = "0.8.2"

